#!/bin/sh

set -o errexit

mkdir -p ebin logs blocks wallets txs

echo "executing with git ref: $(git show-ref -s --head HEAD)"

if [ -t 1 ]; then
	SHELL_OPTS=
else
	SHELL_OPTS=-noinput
fi

erlc +export_all -o ebin/ src/ar.erl
exec erl $SHELL_OPTS -pa ebin/ -s ar rebuild -run ar main "$@"
