#!/bin/sh

set -o errexit

mkdir -p ebin logs blocks wallets txs blocks/enc priv

if [ -t 1 ]; then
	SHELL_OPTS=
else
	SHELL_OPTS=-noinput
fi

exec erl $SHELL_OPTS -pa ebin/ -s ar rebuild -run ar main "$@"
