%%% @doc Fixture and deterministic-time runner for chunk-sync simulations.
%%%
%%% The runner installs ar_sync_deps_sim behind the real sync pipeline,
%%% drives the pipeline on ar_timer's simulated clock, and exposes snapshots
%%% used by simulation scenarios.
-module(ar_sync_sim_runner).
-test_category([fast]).

-export([setup_sim/2]).
-export([start_sim/1, update_world/1, run_for/1, advance_tick/0, flush_pipeline/0]).
-export([metric/2]).

-include_lib("arweave/include/ar.hrl").
-include_lib("arweave/include/ar_consensus.hrl").
-include_lib("arweave/include/ar_sync.hrl").
-include_lib("eunit/include/eunit.hrl").
-include("ar_sync_sim.hrl").

%% Workers and cache mirror the s1 test-rig config; the store count just
%% needs to be comfortably plural (sweep cost is per store).
%% The 2000 MiB total sync-cache budget resolves through production's 90/10
%% split to the historical 7200-chunk simulator cache.
-define(SIM_CACHE_SIZE_MIB, 2000).
%% The ar_sync_scheduler tick, shrunk from the production 10s: every per-tick
%% dynamic (cap growth, EWMA folds, timeout rotations) is tick-denominated,
%% so a shorter tick only cuts the simulated seconds each tick drags in.
-define(SIM_TICK_MS, 1000).
%% Sub-steps per simulated second -- equivalently, the round trips a
%% fully-busy worker completes per second (one per sub-step).
-define(SUBSTEPS_PER_SECOND, (1000 div ?SIM_SUBSTEP_MS)).
%% Generous deadman against genuinely lost sleepers. Mainnet-sized footprints
%% can spend several wall-clock seconds computing between sleeps.
-define(WORKERS_ASLEEP_TIMEOUT_MS, 60_000).

%% @doc Return an EUnit fixture for a simulation test.
setup_sim(TestFun, Timeout) ->
    {setup,
        fun setup_fixture/0,
        fun teardown_fixture/1,
        {test_name(TestFun), {timeout, Timeout, fun() ->
            arweave_config:with_test_config(TestFun)
        end}}}.

setup_fixture() ->
    ar_sync_sim_world:create(),
    ar_sync_deps:override_module(ar_sync_deps_sim),
    %% Production-scale sweep windows and the short simulation scheduler
    %% tick are hot-path persistent_term overrides, not mocks.
    ar_sync_cursor:override_query_range_step_size(?QUERY_RANGE_STEP_SIZE),
    ar_sync_scheduler:override_tick_interval_ms(?SIM_TICK_MS),
    PreviousDiskPoolThreshold = ar_disk_pool:get_threshold(),
    %% Keep the footprint cursor live through the complete fixed simulation weave.
    ar_disk_pool:set_threshold(ar_sync_sim_world:weave_size()),
    PreviousDiskPoolThreshold.

teardown_fixture(PreviousDiskPoolThreshold) ->
    stop_pipeline(),
    ar_timer:stop_simulated_time(),
    ar_disk_pool:set_threshold(PreviousDiskPoolThreshold),
    ar_sync_cursor:reset_all_overrides(),
    ar_sync_scheduler:reset_all_overrides(),
    ar_sync_deps:reset_all_overrides(),
    ar_block:reset_all_overrides(),
    ar_replica_2_9:reset_all_overrides(),
    ar_sync_sim_world:delete(),
    %% Re-arm the sync subtree from the restored configuration and on the real
    %% clock for later tests.
    catch supervisor:restart_child(ar_data_sync_sup, ar_sync_sup),
    ok.

test_name(TestFun) ->
    {name, Name} = erlang:fun_info(TestFun, name),
    atom_to_list(Name).

%% @doc Configure one initial world and start the real sync pipeline.
start_sim(#sim_world{} = World) ->
    stop_pipeline(),
    %% The packing supervisor owns a process-wide cache. Empty it so entropy
    %% generated by one scenario cannot affect the next scenario.
    ok = ar_entropy_cache:clean_up_space(0, 0),
    NodeConfig0 = maps:merge(default_node_config(), World#sim_world.node_config),
    %% Store topology is fixed for every scenario; node_config controls all other
    %% production settings used by the simulation.
    NodeConfig = NodeConfig0#{
        [storage_modules] => ar_sync_sim_world:storage_modules()},
    ok = arweave_config:force_config(NodeConfig),
    ar_timer:start_simulated_time(),
    ar_sync_sim_world:reset(World),
    ar_sync_discovery:reset_all_caches(),
    start_pipeline(),
    ar_sync_sim_world:start_scenario(),
    ok.

%% @doc Apply a runtime world change and expose its current peers to discovery.
update_world(#sim_world{} = World) ->
    PreviousWorld = ar_sync_sim_world:get(world),
    ar_sync_sim_world:update_world(World),
    maybe_collect_peers(PreviousWorld, World).

maybe_collect_peers(#sim_world{ peers = Peers }, #sim_world{ peers = Peers }) ->
    ok;
maybe_collect_peers(_PreviousWorld, _World) ->
    collect_peers().

collect_peers() ->
    ar_sync_discovery:collect_peers().

start_pipeline() ->
    {ok, _} = supervisor:restart_child(ar_data_sync_sup, ar_sync_sup),
    WeaveSize = ar_sync_sim_world:weave_size(),
    [begin
        ok = ar_sync_store_sweeper:set_weave_size(StoreID, WeaveSize),
        drain_sweeper(StoreID)
    end || StoreID <- ar_sync_sim_world:store_ids()],
    collect_peers(),
    [begin
        ok = ar_sync:start_store(StoreID),
        drain_sweeper(StoreID)
    end || StoreID <- ar_sync_sim_world:store_ids()],
    %% Start simulated time from a stable mailbox boundary. This only waits for
    %% already-started workers to park at time zero; metadata remains unresolved
    %% and the sweepers discover it through their normal polling loop.
    wait_until_workers_sleep(),
    ok.

drain_sweeper(StoreID) ->
    pong = gen_server:call(ar_sync_store_sweeper:name(StoreID), ping),
    ok.

stop_pipeline() ->
    %% Discovery and the scheduler terminate the exact workers they own.
    _ = catch supervisor:terminate_child(ar_data_sync_sup, ar_sync_sup),
    ok.

default_node_config() ->
    #{
        [sync, cache_size] => ?SIM_CACHE_SIZE_MIB,
        [disable_device_limit] => true
    }.

%% @doc Return the number of simulated seconds in one scheduler tick.
seconds_per_tick() ->
    ar_sync_scheduler:tick_interval_ms() div 1000.

%% @doc Advance the simulation by whole scheduler ticks and return the measured change.
run_for(Ticks) when is_integer(Ticks), Ticks > 0 ->
    Before = ar_sync_sim_world:snapshot(),
    do_run_for(Ticks),
    #sim_measurement{
        duration_seconds = Ticks * seconds_per_tick(),
        before_snapshot = Before,
        after_snapshot = ar_sync_sim_world:snapshot()
    }.

do_run_for(0) ->
    ok;
do_run_for(Ticks) ->
    advance_tick(),
    do_run_for(Ticks - 1).

%% @doc Advance one scheduler tick and settle each worker wave.
advance_tick() ->
    lists:foreach(fun(_) -> advance_second() end,
        lists:seq(1, seconds_per_tick())).

advance_second() ->
    lists:foreach(
        fun(_) ->
            ok = ar_timer:advance(?SIM_SUBSTEP_MS),
            wait_until_workers_sleep()
        end,
        lists:seq(1, ?SUBSTEPS_PER_SECOND)).

wait_until_workers_sleep() ->
    wait_until_workers_sleep(erlang:monotonic_time(millisecond)
        + ?WORKERS_ASLEEP_TIMEOUT_MS).

wait_until_workers_sleep(Deadline) ->
    flush_pipeline(),
    FetchInflight = ar_sync_scheduler:inflight_count(),
    Sleeping = ar_timer:sleeping(),
    DiscoveryInflight = case catch ar_sync_discovery:inflight_count() of
        N when is_integer(N) -> N;
        _ -> 0
    end,
    case FetchInflight + DiscoveryInflight =:= Sleeping of
        true ->
            ok;
        false ->
            case erlang:monotonic_time(millisecond) > Deadline of
                true ->
                    Rows = ets:tab2list(ar_timer_simulated),
                    Pids = [element(2, Msg) || {_, Msg, _} <- Rows,
                        is_tuple(Msg), element(1, Msg) =:= msg],
                    Stacks = [{Pid,
                        catch erlang:process_info(Pid, current_stacktrace)}
                        || Pid <- Pids, is_pid(Pid)],
                    error({workers_still_awake, FetchInflight, DiscoveryInflight,
                        Sleeping, Stacks});
                false ->
                    erlang:yield(),
                    wait_until_workers_sleep(Deadline)
            end
    end.

%% @doc Flush casts queued in the scheduler, generators, and discovery.
flush_pipeline() ->
    [catch gen_server:call(ar_sync_store_sweeper:name(StoreID), ping)
        || StoreID <- ar_sync_sim_world:store_ids()],
    catch gen_server:call(ar_sync_scheduler, ping),
    %% Force DOWN processing so metadata job membership converges with the
    %% simulated clock's sleeper count.
    catch ar_sync_discovery:inflight_count(),
    catch gen_server:call(ar_sync_scheduler, ping),
    [catch gen_server:call(ar_sync_store_sweeper:name(StoreID), ping)
        || StoreID <- ar_sync_sim_world:store_ids()],
    catch gen_server:call(ar_sync_scheduler, ping),
    ok.

%% @doc Return an interval metric, or one value from a map-valued metric.
metric({Metric, Key}, Measurement) ->
    maps:get(Key, metric(Metric, Measurement), 0);
metric(duration_seconds, #sim_measurement{ duration_seconds = Seconds }) ->
    Seconds;
metric(cps_by_peer, Measurement) ->
    Seconds = metric(duration_seconds, Measurement),
    maps:map(fun(_Peer, Count) -> Count / Seconds end,
        metric(served_by_peer, Measurement));
metric(served_by_peer, Measurement) ->
    map_counter_difference(#sim_snapshot.served_by_peer, Measurement);
metric(rejected_by_peer, Measurement) ->
    map_counter_difference(#sim_snapshot.rejected_by_peer, Measurement);
metric(timed_out_by_peer, Measurement) ->
    map_counter_difference(#sim_snapshot.timed_out_by_peer, Measurement);
metric(client_errors_by_peer, Measurement) ->
    map_counter_difference(#sim_snapshot.client_errors_by_peer, Measurement);
metric(chunk_interval_requests_by_peer, Measurement) ->
    map_counter_difference(
        #sim_snapshot.chunk_interval_requests_by_peer, Measurement);
metric(chunks_stored_by_store, Measurement) ->
    map_counter_difference(#sim_snapshot.chunks_stored_by_store, Measurement);
metric(chunks_stored_total, Measurement) ->
    lists:sum(maps:values(metric(chunks_stored_by_store, Measurement)));
metric(stored_cps, Measurement) ->
    metric(chunks_stored_total, Measurement)
        / metric(duration_seconds, Measurement);
metric(final_http_inflight_by_peer, #sim_measurement{
        after_snapshot = #sim_snapshot{ http_inflight_by_peer = HTTPInflight }
    }) ->
    HTTPInflight;
metric(final_chunk_interval_requests_by_peer, #sim_measurement{
        after_snapshot = #sim_snapshot{
            chunk_interval_requests_by_peer = ChunkIntervalRequests
        }
    }) ->
    ChunkIntervalRequests;
metric(final_chunk_interval_inflight_by_peer, #sim_measurement{
        after_snapshot = #sim_snapshot{
            chunk_interval_inflight_by_peer = ChunkIntervalInflight
        }
    }) ->
    ChunkIntervalInflight.

map_counter_difference(FieldIndex, #sim_measurement{
        before_snapshot = Before,
        after_snapshot = After
    }) ->
    map_difference(element(FieldIndex, Before), element(FieldIndex, After)).

map_difference(Before, After) ->
    maps:fold(
        fun(Key, BeforeValue, Difference) ->
            maps:update_with(Key,
                fun(AfterValue) -> AfterValue - BeforeValue end,
                -BeforeValue,
                Difference)
        end,
        After,
        Before).
%%%===================================================================
%%% Tests.
%%%===================================================================

%% #sim_world.node_config drives the production sync-cache calculation used to
%% initialize the world; simulated store topology remains fixed.
node_config_drives_cache_capacity_test_() ->
    setup_sim(fun test_node_config_drives_cache_capacity/0, 30).

test_node_config_drives_cache_capacity() ->
    %% 1000 MiB holds 4000 256 KiB chunks; production assigns 90% (3600)
    %% to fetched chunks and the remaining 10% to chunk interval requests.
    CacheMiB = 1000,
    ExpectedChunkCacheLimit = 3600,
    start_sim(#sim_world{
        node_config = #{
            [sync, cache_size] => CacheMiB
        }
    }),
    ?assertEqual(ExpectedChunkCacheLimit, ar_data_sync:chunk_cache_size_limit()),
    ?assertEqual(ExpectedChunkCacheLimit, ar_sync_sim_world:get(cache_limit)).
