%%% @doc Shared protocol constants, geometry, and fork heights.
-module(arweave_constants).

-include_lib("arweave_constants/include/arweave_constants.hrl").

-export([
    partition_size/0,
    strict_data_split_threshold/0,
    get_merkle_rebase_support_threshold/0,
    get_consensus_window_size/0,
    get_max_tx_anchor_depth/0,
    get_max_timestamp_deviation/0,
    replica_2_9_entropy_size/0,
    replica_2_9_entropy_count/0,
    get_replica_2_9_entropy_sector_size/0,
    get_replica_2_9_entropy_partition_size/0,
    get_sub_chunks_per_replica_2_9_entropy/0,
    get_replica_2_9_footprint_size/0,
    get_replica_2_9_footprints_per_partition/0,
    get_recall_range_size/1,
    get_sub_chunk_size/1,
    get_nonces_per_chunk/1,
    get_nonces_per_recall_range/1,
    get_max_nonce/1,
    get_chunk_padded_offset/1,
    get_padded_offset/2
]).
-export([
    height_1_6/0,
    height_1_7/0,
    height_1_8/0,
    height_1_9/0,
    height_2_0/0,
    height_2_2/0,
    height_2_3/0,
    height_2_4/0,
    height_2_5/0,
    height_2_6/0,
    height_2_6_8/0,
    height_2_7/0,
    height_2_7_1/0,
    height_2_7_2/0,
    height_2_8/0,
    height_2_9/0,
    height_2_9_6/0
]).

-ifdef(AR_TEST).
-export([
    internal_override_partition_size/1,
    internal_reset_partition_size_override/0,
    internal_override_replica_2_9_entropy_size/1,
    internal_override_replica_2_9_entropy_count/1,
    internal_reset_replica_2_9_overrides/0
]).

%% Test-only overrides let simulations exercise mainnet-sized footprints.
%% All applications read the same values, including derived geometry.
partition_size() ->
    persistent_term:get({?MODULE, partition_size}, ?PARTITION_SIZE).

replica_2_9_entropy_size() ->
    persistent_term:get({?MODULE, entropy_size}, ?REPLICA_2_9_ENTROPY_SIZE).

replica_2_9_entropy_count() ->
    persistent_term:get({?MODULE, entropy_count}, ?REPLICA_2_9_ENTROPY_COUNT).

internal_override_partition_size(Size) ->
    persistent_term:put({?MODULE, partition_size}, Size).

internal_reset_partition_size_override() ->
    persistent_term:erase({?MODULE, partition_size}),
    ok.

internal_override_replica_2_9_entropy_size(Size) ->
    persistent_term:put({?MODULE, entropy_size}, Size).

internal_override_replica_2_9_entropy_count(Count) ->
    persistent_term:put({?MODULE, entropy_count}, Count).

internal_reset_replica_2_9_overrides() ->
    persistent_term:erase({?MODULE, entropy_size}),
    persistent_term:erase({?MODULE, entropy_count}),
    ok.
-else.
%% @doc Return the size in bytes of a mining partition.
partition_size() ->
    ?PARTITION_SIZE.

%% @doc Return the number of bytes generated by one replica.2.9 entropy.
replica_2_9_entropy_size() ->
    ?REPLICA_2_9_ENTROPY_SIZE.

%% @doc Return the number of replica.2.9 entropies generated per partition.
replica_2_9_entropy_count() ->
    ?REPLICA_2_9_ENTROPY_COUNT.
-endif.

%% @doc Return the offset above which chunks use strict split padding.
strict_data_split_threshold() ->
    ?STRICT_DATA_SPLIT_THRESHOLD.

%% @doc Return the offset above which data paths support offset rebasing.
get_merkle_rebase_support_threshold() ->
    ?MERKLE_REBASE_SUPPORT_THRESHOLD.

%% @doc Return the number of recent blocks accepted during consensus.
get_consensus_window_size() ->
    ?STORE_BLOCKS_BEHIND_CURRENT.

%% @doc Return the maximum allowed depth of a transaction's block anchor.
get_max_tx_anchor_depth() ->
    ?MODULE:get_consensus_window_size().

%% @doc Return the maximum allowed backwards timestamp change in seconds.
get_max_timestamp_deviation() ->
    ?JOIN_CLOCK_TOLERANCE * 2 + ?CLOCK_DRIFT_MAX.

%% @doc Return the contiguous byte range with unique replica.2.9 entropies.
get_replica_2_9_entropy_sector_size() ->
    ?MODULE:replica_2_9_entropy_count() * ?SUB_CHUNK_SIZE.

%% @doc Return the size in bytes of a replica.2.9 entropy partition.
get_replica_2_9_entropy_partition_size() ->
    ?MODULE:replica_2_9_entropy_count() * ?MODULE:replica_2_9_entropy_size().

%% @doc Return the number of sub-chunks served by one replica.2.9 entropy.
get_sub_chunks_per_replica_2_9_entropy() ->
    ?MODULE:replica_2_9_entropy_size() div ?SUB_CHUNK_SIZE.

%% @doc Return the total entropy size in bytes for a replica.2.9 footprint.
get_replica_2_9_footprint_size() ->
    ?MODULE:replica_2_9_entropy_size() * ?SUB_CHUNK_COUNT.

%% @doc Return the number of replica.2.9 footprints in an entropy partition.
get_replica_2_9_footprints_per_partition() ->
    ?MODULE:replica_2_9_entropy_count() div ?SUB_CHUNK_COUNT.

%% @doc Return the recall range size in bytes for the packing difficulty.
get_recall_range_size(0) ->
    ?LEGACY_RECALL_RANGE_SIZE;
get_recall_range_size(PackingDifficulty) ->
    ?RECALL_RANGE_SIZE div PackingDifficulty.

%% @doc Return the bytes per mining nonce for the packing difficulty.
get_sub_chunk_size(0) ->
    ?DATA_CHUNK_SIZE;
get_sub_chunk_size(_PackingDifficulty) ->
    ?SUB_CHUNK_SIZE.

%% @doc Return the number of mining nonces contained in each data chunk.
get_nonces_per_chunk(0) ->
    1;
get_nonces_per_chunk(_PackingDifficulty) ->
    ?SUB_CHUNK_COUNT.

%% @doc Return the number of mining nonces in one recall range.
get_nonces_per_recall_range(PackingDifficulty) ->
    %% Use the public call so recall range overrides also affect this value.
    max(
        1,
        ?MODULE:get_recall_range_size(PackingDifficulty) div
            get_sub_chunk_size(PackingDifficulty)
    ).

%% @doc Return the largest mining nonce for the packing difficulty.
get_max_nonce(PackingDifficulty) ->
    %% Test recall ranges can be smaller than a chunk.
    max(
        get_nonces_per_chunk(PackingDifficulty) - 1,
        get_nonces_per_recall_range(PackingDifficulty) - 1
    ).

%% @doc Pad offsets above the strict split threshold to their chunk end.
get_chunk_padded_offset(Offset) ->
    Threshold = ?MODULE:strict_data_split_threshold(),
    case Offset > Threshold of
        true -> get_padded_offset(Offset, Threshold);
        false -> Offset
    end.

%% @doc Round Offset up to a chunk boundary measured from Threshold.
get_padded_offset(Offset, Threshold) ->
    Diff = Offset - Threshold,
    Threshold + ((Diff - 1) div ?DATA_CHUNK_SIZE + 1) * ?DATA_CHUNK_SIZE.

%% @doc Return the activation height of fork 1.6.
height_1_6() ->
    arweave_constants_fork:height_1_6().

%% @doc Return the activation height of fork 1.7.
height_1_7() ->
    arweave_constants_fork:height_1_7().

%% @doc Return the activation height of fork 1.8.
height_1_8() ->
    arweave_constants_fork:height_1_8().

%% @doc Return the activation height of fork 1.9.
height_1_9() ->
    arweave_constants_fork:height_1_9().

%% @doc Return the activation height of fork 2.0.
height_2_0() ->
    arweave_constants_fork:height_2_0().

%% @doc Return the activation height of fork 2.2.
height_2_2() ->
    arweave_constants_fork:height_2_2().

%% @doc Return the activation height of fork 2.3.
height_2_3() ->
    arweave_constants_fork:height_2_3().

%% @doc Return the activation height of fork 2.4.
height_2_4() ->
    arweave_constants_fork:height_2_4().

%% @doc Return the activation height of fork 2.5.
height_2_5() ->
    arweave_constants_fork:height_2_5().

%% @doc Return the activation height of fork 2.6.
height_2_6() ->
    arweave_constants_fork:height_2_6().

%% @doc Return the activation height of fork 2.6.8.
height_2_6_8() ->
    arweave_constants_fork:height_2_6_8().

%% @doc Return the activation height of fork 2.7.
height_2_7() ->
    arweave_constants_fork:height_2_7().

%% @doc Return the activation height of fork 2.7.1.
height_2_7_1() ->
    arweave_constants_fork:height_2_7_1().

%% @doc Return the activation height of fork 2.7.2.
height_2_7_2() ->
    arweave_constants_fork:height_2_7_2().

%% @doc Return the activation height of fork 2.8.
height_2_8() ->
    arweave_constants_fork:height_2_8().

%% @doc Return the activation height of fork 2.9.
height_2_9() ->
    arweave_constants_fork:height_2_9().

%% @doc Return the activation height of fork 2.9.6.
height_2_9_6() ->
    arweave_constants_fork:height_2_9_6().
