-ifndef(AR_GLOBAL_SYNC_RECORD_HRL).
-define(AR_GLOBAL_SYNC_RECORD_HRL, true).

-ifndef(AR_GLOBAL_SYNC_RECORD_SKIP_REPLICA_2_9).
-define(AR_GLOBAL_SYNC_RECORD_SKIP_REPLICA_2_9, true).
-else.
-define(AR_GLOBAL_SYNC_RECORD_SKIP_REPLICA_2_9, false).
-endif.

-endif.
